version: "3"
services:
  app:
    container_name: portfolio
    image: portfolio_image
    build:
      context: ./docker/httpd
      dockerfile: Dockerfile
    expose:
      - "80"
    volumes:
      - ./:/var/www/html
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

      - "traefik.http.middlewares.portfolio-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.portfolio-redirectscheme.redirectscheme.permanent=true"

      - "traefik.http.routers.portfolio.rule=Host(`andyle.info`)"
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.http.routers.portfolio.middlewares=portfolio-redirectscheme"

      - "traefik.http.routers.portfolio-secure.rule=Host(`andyle.info`)"
      - "traefik.http.routers.portfolio-secure.entrypoints=websecure"
      - "traefik.http.routers.portfolio-secure.service=portfolio"
      - "traefik.http.routers.portfolio-secure.tls=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy